return {
    mod_name = { en = "BallHammer" },
    mod_description = { en = "All-enemy ESP with persistent aim, triggerbot, rage, and weapon controls" },

    esp_settings = { en = "ESP" },
    enable_outlines = { en = "Enemy Outlines" },
    outline_distance = { en = "Outline Distance (m)" },
    enable_nameplates = { en = "Special Enemy Boxes" },
    max_distance = { en = "Special Box Distance (m)" },
    enable_horde_esp = { en = "All-Enemy Dynamic Boxes" },
    horde_distance = { en = "Dynamic Box Distance (m)" },
    toggle_key = { en = "Toggle ESP Keybind" },

    pickup_settings = { en = "Pickup ESP" },
    enable_pickup_esp = { en = "Show Pickups" },
    pickup_distance = { en = "Pickup Distance (m)" },
    pickup_filter = { en = "Pickup Filter" },
    pickup_filter_all = { en = "All Pickups" },
    pickup_filter_supplies = { en = "Supplies" },
    pickup_filter_stimms = { en = "Stims" },
    pickup_filter_materials = { en = "Crafting Materials" },
    pickup_filter_mission = { en = "Mission Items" },
    pickup_filter_custom = { en = "Custom" },
    pickup_show_plasteel = { en = "Plasteel" },
    pickup_show_diamantine = { en = "Diamantine" },
    pickup_show_ammo = { en = "Ammo" },
    pickup_show_ammo_crate = { en = "Ammo Crates" },
    pickup_show_grenade = { en = "Grenades" },
    pickup_show_medkit = { en = "Medkits" },
    pickup_show_med_stimm = { en = "Med Stimms" },
    pickup_show_concentration_stimm = { en = "Concentration Stimms" },
    pickup_show_combat_stimm = { en = "Combat Stimms" },
    pickup_show_celerity_stimm = { en = "Celerity Stimms" },
    pickup_show_grimoire = { en = "Grimoires" },
    pickup_show_scripture = { en = "Scriptures" },
    pickup_show_other = { en = "Other Pickups" },

    aimbot_settings = { en = "Aimbot" },
    aim_activation = { en = "Aim Activation" },
    aim_activation_off = { en = "Off" },
    aim_activation_left = { en = "Left Mouse" },
    aim_activation_right = { en = "Right Mouse" },
    aim_activation_both = { en = "Either Left or Right Mouse" },
    aim_activation_custom = { en = "Custom Keyboard Key" },
    aim_key = { en = "Custom Aim Key (keyboard only)" },
    aim_location = { en = "Aim Location" },
    aim_location_head = { en = "Head" },
    aim_location_torso = { en = "Torso" },
    aim_distance = { en = "Aim Distance (m)" },
    aim_fov = { en = "Aim Field of View (degrees)" },
    show_aim_fov = { en = "Show Target FOV Circle" },
    aim_fov_opacity = { en = "FOV Circle Opacity (%%)" },
    aim_fov_red = { en = "FOV Circle Red" },
    aim_fov_green = { en = "FOV Circle Green" },
    aim_fov_blue = { en = "FOV Circle Blue" },
    aim_smoothness = { en = "Aim Smoothness" },
    aim_curve = { en = "Aim Curve" },

    triggerbot_settings = { en = "Magnet Triggerbot" },
    trigger_activation = { en = "Trigger Activation" },
    trigger_key = { en = "Custom Trigger Key (keyboard only)" },
    trigger_fov = { en = "Magnet Field of View (degrees)" },
    trigger_fire_fov = { en = "Fire Radius (degrees)" },
    trigger_smoothness = { en = "Magnet Smoothness" },

    rage_settings = { en = "Rage Mode" },
    rage_key = { en = "Hold Rage Key" },
    rage_distance = { en = "Rage Distance (m)" },
    rage_smoothness = { en = "Rage Smoothness" },

    director_settings = { en = "Armor and Weakspot Director" },
    enable_aim_director = { en = "Armor-Aware Hit Zones" },

    threat_settings = { en = "Threat Interceptor" },
    enable_threat_markers = { en = "Threat Reaction Markers" },
    enable_threat_reactions = { en = "Automatic Threat Reactions (Diagnostic)" },
    reaction_timing = { en = "Reaction Timing (Early to Late)" },
    emergency_override = { en = "Immediate Emergency Override Physical Input" },
    enable_survival_debug = { en = "Diagnostic Logging" },

    guard_settings = { en = "Guard Brain" },
    enable_guard_brain = { en = "Automatic Block and Push (Diagnostic)" },
    stamina_reserve = { en = "Push Stamina Reserve (%%)" },

    governor_settings = { en = "Warp and Heat Governor" },
    enable_resource_governor = { en = "Prevent Unsafe Attacks" },
    enable_auto_vent = { en = "Auto-Quell or Safe Vent" },
    peril_target = { en = "Peril Safety Target (%%)" },
    heat_target = { en = "Heat Safety Target (%%)" },

    weapon_settings = { en = "Weapon" },
    enable_auto_fire = { en = "Automatic Semi-Auto Fire" },
    enable_no_recoil = { en = "No Recoil" },
    enable_no_spread = { en = "No Spread" },

    companion_settings = { en = "Companion" },
    enable_companion_target = { en = "Auto-Target Specials" },
    companion_distance = { en = "Auto-Target Distance (m)" },
    enable_auto_whistle = { en = "Auto-Use Dog EMP" },
}
