return {
    mod_name = { en = "BallHammer" },
    mod_description = { en = "All-enemy ESP with persistent, visibility-aware normal aim" },

    esp_settings = { en = "ESP" },
    enable_outlines = { en = "Enemy Outlines" },
    outline_distance = { en = "Outline Distance (m)" },
    enable_nameplates = { en = "Special Enemy Boxes" },
    max_distance = { en = "Special Box Distance (m)" },
    enable_horde_esp = { en = "All-Enemy Dynamic Boxes" },
    horde_distance = { en = "Dynamic Box Distance (m)" },
    toggle_key = { en = "Toggle ESP Keybind" },

    aimbot_settings = { en = "Aimbot" },
    aim_activation = { en = "Aim Activation" },
    aim_activation_off = { en = "Off" },
    aim_activation_left = { en = "Left Mouse" },
    aim_activation_right = { en = "Right Mouse" },
    aim_activation_both = { en = "Either Left or Right Mouse" },
    aim_activation_custom = { en = "Custom Keyboard Key" },
    aim_key = { en = "Custom Aim Key (keyboard only)" },
    aim_location = { en = "Aim Location" },
    aim_location_head = { en = "Head" },
    aim_location_torso = { en = "Torso" },
    aim_distance = { en = "Aim Distance (m)" },
    aim_fov = { en = "Aim Field of View (degrees)" },
    aim_smoothness = { en = "Aim Smoothness" },
    aim_curve = { en = "Aim Curve" },
}
